[package]
name = "curve_ray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
cgmath = {version = "*", features = ["swizzle"]}
bvh = "*"
[dev-dependencies]
criterion = "*"
